---
version: "3"

services:
  vector:
    image: timberio/vector:0.23.0-debian
    container_name: vector
    ports:
      - 8888:8888
    volumes: 
      - $PWD/vector.toml:/etc/vector/vector.toml:ro
    environment:
      DCCONNECT: ${DCCONNECT}
      DCUSER: ${DCUSER}
      DCPASS: ${DCPASS}

  grafana:
    build: .
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
          - name: 'ClickHouse'
            type: 'grafana-clickhouse-datasource'
            isDefault: true
            jsonData:
              defaultDatabase: vector
              port: ${NATIVEPORT}
              server: ${DCHOST} 
              username: ${DCUSER}
              tlsSkipVerify: false
              secure: true
            secureJsonData:
              password: ${DCPASS}
            editable: true
        EOF
        mkdir -p /etc/grafana/provisioning/dashboards
        cat <<EOF > /etc/grafana/provisioning/dashboards/dashboard.yaml
        apiVersion: 1
        providers:
          - name: demo-logs
            type: file
            updateIntervalSeconds: 30
            options:
              path:  /var/lib/grafana/dashboards
              foldersFromFilesStructure: true
        EOF
        /run.sh
    ports:
      - "3000:3000"
